server:
  port: 8080

spring:
  profiles:
    active: local # 기본적으로 활성화할 profile을 local로 설정

---
jasypt:
  encryptor:
    bean: jasyptEncryptorAES
    password: cinesquare

spring:
  config:
    activate:
      on-profile: local

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB # 파일 업로드 크기 설정
      max-request-size: 20MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cinesquare
    username: ENC(9quXXHScEVuQHxY5o4sFfIa67tV8gtIb0EtHd9lmZEVbfyj7rf+dMpV1l0pgZEh/)
    password: ENC(/YUs9sVzMKU9iQdrCfjyCjOFQZE2Td9KROPqa5kWrbfrToNiNh+OthVQSzueBgfd)
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

cloud:
  aws:
    credentials:
      accessKey: ENC(hDOv8QuiagVolVEqtZ6ASRVMAcia9WkOSE9LlUQGTdFdgpfZPxZs/zoOQTY3W3DyM5oK/bhTR9UACQToPT4IEw==)
      secretKey: ENC(Cwf8yv+X1y/VBmG5V2eG45q3eURyQh8WOov/ADAFcAmYpGGiCeZrZfRC5fmrFbqGxaGkmwyI4M7MjLxp0Bo0FzRRX2YXZwfKIv4gsaFoeno=)
    s3:
      bucket: cinesquares3
      url: https://s3.ap-northeast-2.amazonaws.com/cinesquares3
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE # parameter 값 보기
    com.p6spy: DEBUG # P6Spy 로깅 설정

springdoc:
  swagger-ui:
    tags-sorter: alpha
    doc-expansion: none

---
jasypt:
  encryptor:
    bean: jasyptEncryptorAES
    password: cinesquare

spring:
  config:
    activate:
      on-profile: dev

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB # 파일 업로드 크기 설정
      max-request-size: 20MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://cinesquare.cbccq00go18j.ap-northeast-2.rds.amazonaws.com:3306/cinesquare
    username: ENC(9quXXHScEVuQHxY5o4sFfIa67tV8gtIb0EtHd9lmZEVbfyj7rf+dMpV1l0pgZEh/)
    password: ENC(qVYf/owe6eMn1T19F2ZkLuDk9V2izqFqUf74o1jr4pv/2m5lgcnDGLQIsmjLxlrPYxvTC/yOQlkpCkmuTcxZzQ==)
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

cloud:
  aws:
    credentials:
      accessKey: ENC(hDOv8QuiagVolVEqtZ6ASRVMAcia9WkOSE9LlUQGTdFdgpfZPxZs/zoOQTY3W3DyM5oK/bhTR9UACQToPT4IEw==)
      secretKey: ENC(Cwf8yv+X1y/VBmG5V2eG45q3eURyQh8WOov/ADAFcAmYpGGiCeZrZfRC5fmrFbqGxaGkmwyI4M7MjLxp0Bo0FzRRX2YXZwfKIv4gsaFoeno=)
    s3:
      bucket: cinesquares3
      url: https://s3.ap-northeast-2.amazonaws.com/cinesquares3
#      weburl: https://cinesquares3.s3.ap-northeast-2.amazonaws.com # 외부에서 접속하는 경우
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE # parameter 값 보기
    com.p6spy: DEBUG # P6Spy 로깅 설정

springdoc:
  swagger-ui:
    tags-sorter: alpha
    doc-expansion: none